export const productStructure = [
  {
    label: 'Nombre',
    formControlName: 'prod_nom',
    type: 'text',
    col: '12',
  },
  {
    label: 'Descripción',
    formControlName: 'prod_descrip',
    type: 'text',
    col: '12',
  },
  {
    label: 'Código Interno',
    formControlName: 'prod_cod_interno',
    type: 'text',
    col: '6',
  },
  {
    label: 'Código Fabricante',
    formControlName: 'cod_fabricante',
    type: 'text',
    col: '6',
  },
  {
    label: 'Categoría',
    formControlName: 'cat_id',
    type: 'select',
    col: '3',
    dataSource: 'categorias',
  },
  {
    label: 'Unidad',
    formControlName: 'und_id',
    type: 'select',
    col: '3',
    dataSource: 'unidades',
  },
  {
    label: 'Moneda',
    formControlName: 'mon_id',
    type: 'select',
    col: '3',
    dataSource: 'monedas',
  },
  {
    label: 'Marca',
    formControlName: 'marca_id',
    type: 'select',
    col: '3',
    dataSource: 'marcas',
  },
  {
    label: 'Precio Compra Base',
    formControlName: 'precio_compra_base',
    type: 'number',
    col: '6',
  },
  {
    label: 'Precio Venta Base',
    formControlName: 'precio_venta_base',
    type: 'number',
    col: '6',
  },
  {
    label: 'Imagen',
    formControlName: 'prod_img',
    type: 'file',
    col: '12',
  },
];
