services:
  factu-front-web:
    image: factu-front-web
    container_name: factu-front-web
    restart: always
    ports:
      - 8081:80
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - factulink-red
networks:
    factulink-red:
      external: true