export const PERMISSIONS = {
  RECRUITERS: {
    CREATE: "reclutador.create",
    EDIT: "reclutador.edit",
    DELETE: "reclutador.delete",
    SAVE: "reclutador.save",
  },
  METRICS: {
    DETAILS: "requerimiento.details",
    DOWNLOAD: "requerimiento.download",
  },
  REQUIREMENTS: {
    CREATE: "requerimiento.create",
    DETAILS: "requerimiento.details",
    DOWNLOAD: "requerimiento.download",
    EDIT: "requerimiento.edit",
    DELETE: "requerimiento.delete",
    SAVE: "requerimiento.save",
    ASSIGN_APPLICANT: "requerimiento.assign_applicant",
    DOWNLOAD_APPLICANT: "requerimiento.download_applicant",
    EDIT_APPLICANT: "requerimiento.edit_applicant",
    EDIT_RECRUITER: "requerimiento.edit_recruiter",
    UNASSIGN_APPLICANT: "requerimiento.unassign_applicant",
    ASSIGN_RECRUITER: "requerimiento.assign_recruiter",
    UNASSIGN_RECRUITER: "requerimiento.unassign_recruiter",
    CREATE_POST: "requerimiento.create_post",
    CHECKLIST: "requerimiento.checklist",
    EDIT_POST: "requerimiento.edit_post",
    SAVE_POST: "requerimiento.save_post",
  },
  APPLICANT: {
    CREATE: "postulante.create",
    ADD_EXPERIENCE: "postulante.add_experience",
    ADD_EDUCATION: "postulante.add_education",
    EDIT_EDUCATION: "postulante.edit_education",
    EDIT_EXPERIENCE: "postulante.edit_experience",
    DELETE_EDUCATION: "postulante.delete_education",
    DELETE_EXPERIENCE: "postulante.delete_experience",
    ADD_SKILL: "postulante.add_skill",
    EDIT_SKILL: "postulante.edit_skill",
    PRINT_CV: "postulante.print_cv",
    EDIT: "postulante.edit",
    DELETE: "postulante.delete",
    SAVE: "postulante.save",
    IMPORT: "postulante.import",
  },
};
